### ISSUE TITLE
Error message after loading network from NDEx

### ISSUE THREAD

**Issue by keiono** [ndexbio/ndex-cytoscape-app#3]
<img width="459" alt="2016-03-15 11 50 41" src="https://cloud.githubusercontent.com/assets/73890/13766342/6013c15e-eaa4-11e5-9e2d-89c312eedf2a.png">

This error will be displayed after loading network from NDEx, although the result looks OK.

**Comment by dexterpratt** [comment]
David, looks like Kei may not have the latest CyNDEx

**Comment by jingjingbic** [comment]
Can't reproduce it.
